Repository VirtoCommerce/vc-module-experience-api, pull requests merged in 2020-08, with the labels that each got.

#39 workflow for modules
  .github/workflows/manual.yml
  samples/VirtoCommerce.Exp.ExtensionSamples/_module.manifest
Labels: review task created

#42 refactoring
  .github/workflows/manual.yml
Labels: review task created

#45 X-Catalog issues
  src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/ExpAvailabilityData.cs
  src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Extensions/PropertyExtensions.cs
  src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/AvailabilityDataType.cs
  src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Schemas/ProductType.cs
Labels: review task created

#48 Changed secret's name
  .github/workflows/manual.yml
Labels: review task created

#56 VP-4042 Fix: implement non-dictionary property extraction
  src/VirtoCommerce.ExperienceApiModule.DigitalCatalog/Extensions/PropertyExtensions.cs
Labels: bug

#59 VP-4120: Docs add x-purchase-reference
  README.md
  docs/CartType.jpeg
  docs/x-purchase-reference.md
Labels: documentation

#62 VP-4118 Docs: catalog reference improvements
  docs/CategoryType.jpeg
  docs/ProductType.jpeg
  docs/filters-and-facets.md
  docs/how-to-use.md
  docs/x-catalog-reference.md
Labels: documentation

#63 VP-4286 Docs: restructure
  README.md
  docs/index.md
  mkdocs.yml
Labels: documentation

#65 Fix tests for CI
  src/XPurchase/VirtoCommerce.XPurchase.Domain.Tests/Aggregates/CartAggregateTests.cs
  src/XPurchase/VirtoCommerce.XPurchase/CartAggregate.cs
  tests/VirtoCommerce.XDigitalCatalog.Tests/Shemas/ProductTypeTests.cs
Labels: review task created
